[package]
name = "example-ws-services"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.9"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
foxglove = { path = "../../foxglove" }
futures = "0.3"
parking_lot = "0.12"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.27", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.26"
tracing = "0.1"
